### ISSUE TITLE
Other themes

### ISSUE THREAD

**Issue by lucasqueiroz** [lucasqueiroz/custom-slack#3]
# Other themes

# Description
I want to add more themes, such as one based in Atom's One Dark and One Light, etc.

**Comment by kyleholliday** [comment]
Hey @lucasqueiroz - are you just trying to add more hex values that correspond to the different pre-sets on your docs? I'd be happy to help out.

**Comment by lucasqueiroz** [comment]
@kyleholliday not exactly just change the colors, but yeah, something like that. Basically getting the current theme and modifying it a bit. Since the main theme isn't 100% done yet, I believe this would be for the sidebar, currently, then when the theme is done, it could be modified to include the other parts.

**Comment by kyleholliday** [comment]
Sounds good man, I'm on it.
