### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by lucasqueiroz** [lucasqueiroz/custom-slack#4]
The documentation needs to be improved, to include installation instructions, and a contributing guide.

**Comment by lucasqueiroz** [comment]
Reopening because this issue is also related to the installation instructions.

**Comment by abhishek71994** [comment]
Can I work on this? Let me know what to document and I'll get it done.

**Comment by lucasqueiroz** [comment]
I believe this one would be better if I did it myself, since there are a lot of details about how to install and credits to other people.
Thanks, though.
